// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // AspNetUserLogins
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class AspNetUserLogin : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public string LoginProvider { get; set; } // LoginProvider (length: 128)
        public string ProviderKey { get; set; } // ProviderKey (length: 128)
        public int PersonId { get; set; } // PersonID

        // Foreign keys
        public virtual Person Person { get; set; } // FK_AspNetUserLogins_Person

        public AspNetUserLogin()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
