// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // City
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class City : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public int StateProvinceId { get; set; } // StateProvinceID
        public string Name { get; set; } // Name (length: 200)
        public System.DateTime Created { get; set; } // Created

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Address> Addresses { get; set; } // Address.FK_Address_City
        public virtual System.Collections.Generic.ICollection<TransportOptionToCityFarePrice> TransportOptionToCityFarePrices { get; set; } // TransportOptionToCityFarePrice.FK_TransportToCityFarePrice_City

        // Foreign keys
        public virtual StateProvince StateProvince { get; set; } // FK_City_StateProvince

        public City()
        {
            Addresses = new System.Collections.Generic.List<Address>();
            TransportOptionToCityFarePrices = new System.Collections.Generic.List<TransportOptionToCityFarePrice>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
