// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // CountryRegion
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class CountryRegion : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public string Abbreviation { get; set; } // abbreviation (length: 2)
        public int? DistanceUnitId { get; set; } // DistanceUnitID
        public int? MoneyUnitId { get; set; } // MoneyUnitID

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Fare> Fares { get; set; } // Fares.FK_Fares_CountryRegion
        public virtual System.Collections.Generic.ICollection<StateProvince> StateProvinces { get; set; } // StateProvince.FK_StateProvince_CountryRegion
        public virtual System.Collections.Generic.ICollection<TransportOptionToCountryFarePrice> TransportOptionToCountryFarePrices { get; set; } // TransportOptionToCountryFarePrice.FK_TransportToCountryFarePrice_CountryRegion

        // Foreign keys
        public virtual DistanceUnit DistanceUnit { get; set; } // FK_CountryRegion_DistanceUnit
        public virtual MoneyUnit MoneyUnit { get; set; } // FK_CountryRegion_MoneyUnit

        public CountryRegion()
        {
            Fares = new System.Collections.Generic.List<Fare>();
            StateProvinces = new System.Collections.Generic.List<StateProvince>();
            TransportOptionToCountryFarePrices = new System.Collections.Generic.List<TransportOptionToCountryFarePrice>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
