// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // CustomerComplaint
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class CustomerComplaint : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public string Email { get; set; } // Email (length: 200)
        public string MobileNumber { get; set; } // MobileNumber (length: 50)
        public string Comment { get; set; } // Comment
        public System.DateTime Created { get; set; } // Created

        public CustomerComplaint()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
