// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // Document
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class Document : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public string Name { get; set; } // Name (length: 200)
        public int? Sort { get; set; } // Sort

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<PersonDocument> PersonDocuments { get; set; } // PersonDocument.FK_PersonDocuments_Documents

        public Document()
        {
            PersonDocuments = new System.Collections.Generic.List<PersonDocument>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
