// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // EmailTemplate
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class EmailTemplate : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public string EmailKey { get; set; } // EmailKey (length: 200)
        public string Subject { get; set; } // Subject (length: 1000)
        public string Body { get; set; } // Body

        public EmailTemplate()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
