// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // Fares
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class Fare : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public int PersonId { get; set; } // PersonID
        public decimal Latitude { get; set; } // Latitude
        public decimal Longitude { get; set; } // Longitude
        public int CountryId { get; set; } // CountryID
        public string OrderTimeZone { get; set; } // OrderTimeZone (length: 200)
        public int TransportOptionId { get; set; } // TransportOptionID
        public bool IsCancelled { get; set; } // IsCancelled
        public System.DateTime PickupTime { get; set; } // PickupTime
        public decimal? DestinationLatitude { get; set; } // DestinationLatitude
        public decimal? DestinationLongitude { get; set; } // DestinationLongitude
        public System.DateTime? FareStartTime { get; set; } // FareStartTime
        public System.DateTime? FareEndTime { get; set; } // FareEndTime
        public decimal? Distance { get; set; } // Distance
        public decimal? Duration { get; set; } // Duration
        public decimal? TotalFarePrice { get; set; } // TotalFarePrice
        public decimal? BaseFare { get; set; } // BaseFare
        public decimal? PerMile { get; set; } // PerMile
        public decimal? PerMinute { get; set; } // PerMinute
        public decimal? SafeRideFee { get; set; } // SafeRideFee
        public bool FareIncreased { get; set; } // FareIncreased
        public decimal? FareIncreasedBy { get; set; } // FareIncreasedBy
        public string FareTracking { get; set; } // FareTracking
        public System.DateTime? ReceiptSentDate { get; set; } // ReceiptSentDate
        public int? ReasonId { get; set; } // ReasonID
        public System.DateTime Created { get; set; } // Created

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<FareToPersonRelation> FareToPersonRelations { get; set; } // FareToPersonRelation.FK_FareToPersonRelation_Fares
        public virtual System.Collections.Generic.ICollection<PersonToCoupon> PersonToCoupons { get; set; } // PersonToCoupon.FK_PersonToCoupon_Fares
        public virtual System.Collections.Generic.ICollection<TransportToFareRelation> TransportToFareRelations { get; set; } // TransportToFareRelation.FK_TransportToFareRelation_Fares

        // Foreign keys
        public virtual CountryRegion CountryRegion { get; set; } // FK_Fares_CountryRegion
        public virtual Person Person { get; set; } // FK_Fares_Person
        public virtual Reason Reason { get; set; } // FK_Fares_Reason
        public virtual TransportOption TransportOption { get; set; } // FK_Fares_TransportOption

        public Fare()
        {
            IsCancelled = false;
            FareIncreased = false;
            FareToPersonRelations = new System.Collections.Generic.List<FareToPersonRelation>();
            PersonToCoupons = new System.Collections.Generic.List<PersonToCoupon>();
            TransportToFareRelations = new System.Collections.Generic.List<TransportToFareRelation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
