// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // FareToPersonRelation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class FareToPersonRelation : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public int FareId { get; set; } // FareID
        public int PersonId { get; set; } // PersonID
        public bool IsPrimary { get; set; } // IsPrimary
        public bool IsSharedAccepted { get; set; } // IsSharedAccepted
        public bool IsPaymentSucceed { get; set; } // IsPaymentSucceed
        public string BraintreePaymentMessage { get; set; } // BraintreePaymentMessage (length: 200)

        // Foreign keys
        public virtual Fare Fare { get; set; } // FK_FareToPersonRelation_Fares
        public virtual Person Person { get; set; } // FK_FareToPersonRelation_Person

        public FareToPersonRelation()
        {
            IsPrimary = false;
            IsSharedAccepted = false;
            IsPaymentSucceed = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
