// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // FareStatus
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class FareStatu : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public string Name { get; set; } // Name (length: 100)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<TransportToFareRelation> TransportToFareRelations { get; set; } // TransportToFareRelation.FK_TransportToFareRelation_FareStatus

        public FareStatu()
        {
            TransportToFareRelations = new System.Collections.Generic.List<TransportToFareRelation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
