// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class GetNearByVehiclesReturnModel
    {
        [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
        public class ResultSetModel1
        {
            public System.Int32 TransportID { get; set; }
            public System.Int32 TransportOptionID { get; set; }
            public System.Decimal latitude { get; set; }
            public System.Decimal longitude { get; set; }
            public System.Double? Distance { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel1> ResultSet1;

        [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
        public class ResultSetModel2
        {
            public System.Int32 TransportID { get; set; }
            public System.Int32 TransportOptionID { get; set; }
            public System.Decimal latitude { get; set; }
            public System.Decimal longitude { get; set; }
            public System.Double? Distance { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel2> ResultSet2;

    }

}
// </auto-generated>
