// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // Location
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class Location : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public int TransportId { get; set; } // TransportID
        public decimal Latitude { get; set; } // latitude
        public decimal Longitude { get; set; } // longitude
        public System.DateTime LocationDate { get; set; } // LocationDate

        // Foreign keys
        public virtual Transport Transport { get; set; } // FK_Location_Transport

        public Location()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
