// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // MoneyUnit
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class MoneyUnit : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public string Symbol { get; set; } // Symbol (length: 50)
        public string Name { get; set; } // Name (length: 100)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<CountryRegion> CountryRegions { get; set; } // CountryRegion.FK_CountryRegion_MoneyUnit

        public MoneyUnit()
        {
            CountryRegions = new System.Collections.Generic.List<CountryRegion>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
