// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // PersonToCoupon
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class PersonToCoupon : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public int PersonId { get; set; } // PersonID
        public int CouponId { get; set; } // CouponID
        public int? FareId { get; set; } // FareID
        public System.DateTime? ActiveAsOf { get; set; } // ActiveAsOf

        // Foreign keys
        public virtual Coupon Coupon { get; set; } // FK_PersonToCoupon_Coupon
        public virtual Fare Fare { get; set; } // FK_PersonToCoupon_Fares
        public virtual Person Person { get; set; } // FK_PersonToCoupon_Person

        public PersonToCoupon()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
