// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // Reason
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class Reason : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public string Description { get; set; } // Description (length: 3000)
        public int RoleId { get; set; } // RoleID
        public int ReasonTypeId { get; set; } // ReasonTypeID

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Fare> Fares { get; set; } // Fares.FK_Fares_Reason
        public virtual System.Collections.Generic.ICollection<TransportToFareRelation> TransportToFareRelations { get; set; } // TransportToFareRelation.FK_TransportToFareRelation_Reason

        // Foreign keys
        public virtual ReasonType ReasonType { get; set; } // FK_Reason_ReasonType
        public virtual Role Role { get; set; } // FK_Reason_Role

        public Reason()
        {
            Fares = new System.Collections.Generic.List<Fare>();
            TransportToFareRelations = new System.Collections.Generic.List<TransportToFareRelation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
