// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // StateProvince
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class StateProvince : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public int CountryRegionId { get; set; } // CountryRegionID
        public string Name { get; set; } // Name (length: 100)
        public string Abbreviation { get; set; } // Abbreviation (length: 2)
        public System.DateTime Created { get; set; } // Created
        public string CreatedBy { get; set; } // CreatedBy (length: 100)
        public System.DateTime? Modified { get; set; } // Modified
        public string ModifiedBy { get; set; } // ModifiedBy (length: 100)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<City> Cities { get; set; } // City.FK_City_StateProvince

        // Foreign keys
        public virtual CountryRegion CountryRegion { get; set; } // FK_StateProvince_CountryRegion

        public StateProvince()
        {
            Cities = new System.Collections.Generic.List<City>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
