// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // TransportOptionToCityFarePrice
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class TransportOptionToCityFarePrice : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public int TransportOptionId { get; set; } // TransportOptionID
        public int CityId { get; set; } // CityID
        public decimal BaseFare { get; set; } // BaseFare
        public decimal PerMile { get; set; } // PerMile
        public decimal PerMinute { get; set; } // PerMinute
        public decimal SafeRideFee { get; set; } // SafeRideFee
        public decimal? IncreasedBy { get; set; } // IncreasedBy
        public bool IsFareIncreased { get; set; } // IsFareIncreased

        // Foreign keys
        public virtual City City { get; set; } // FK_TransportToCityFarePrice_City
        public virtual TransportOption TransportOption { get; set; } // FK_TransportOptionToCityFarePrice_TransportOption

        public TransportOptionToCityFarePrice()
        {
            IsFareIncreased = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
