// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // TransportOptionToCountryFarePrice
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class TransportOptionToCountryFarePrice : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public int TransportOptionId { get; set; } // TransportOptionID
        public int CountryRegionId { get; set; } // CountryRegionID
        public decimal BaseFare { get; set; } // BaseFare
        public decimal PerMile { get; set; } // PerMile
        public decimal PerMinute { get; set; } // PerMinute
        public decimal SafeRideFee { get; set; } // SafeRideFee

        // Foreign keys
        public virtual CountryRegion CountryRegion { get; set; } // FK_TransportToCountryFarePrice_CountryRegion
        public virtual TransportOption TransportOption { get; set; } // FK_TransportOptionToCountryFarePrice_TransportOption

        public TransportOptionToCountryFarePrice()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
