// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // TransportToFareRelation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class TransportToFareRelation : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public int TransportId { get; set; } // TransportID
        public int FareId { get; set; } // FareID
        public int FareStatusId { get; set; } // FareStatusID
        public System.DateTime? FareAcceptedDate { get; set; } // FareAcceptedDate
        public bool IsFareAcceptedAcknowledged { get; set; } // IsFareAcceptedAcknowledged
        public bool IsCalledOut { get; set; } // IsCalledOut
        public bool IsCallOutAcknowledged { get; set; } // IsCallOutAcknowledged
        public int? MinutesOut { get; set; } // MinutesOut
        public int? ReasonId { get; set; } // ReasonID

        // Foreign keys
        public virtual Fare Fare { get; set; } // FK_TransportToFareRelation_Fares
        public virtual FareStatu FareStatu { get; set; } // FK_TransportToFareRelation_FareStatus
        public virtual Reason Reason { get; set; } // FK_TransportToFareRelation_Reason
        public virtual Transport Transport { get; set; } // FK_TransportToFareRelation_Transport

        public TransportToFareRelation()
        {
            IsFareAcceptedAcknowledged = false;
            IsCalledOut = false;
            IsCallOutAcknowledged = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
