// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // TransportOption
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class TransportOption : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public int TransportTypeId { get; set; } // TransportTypeID

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Fare> Fares { get; set; } // Fares.FK_Fares_TransportOption
        public virtual System.Collections.Generic.ICollection<Transport> Transports { get; set; } // Transport.FK_Transport_TransportOption
        public virtual System.Collections.Generic.ICollection<TransportOptionToCityFarePrice> TransportOptionToCityFarePrices { get; set; } // TransportOptionToCityFarePrice.FK_TransportOptionToCityFarePrice_TransportOption
        public virtual System.Collections.Generic.ICollection<TransportOptionToCountryFarePrice> TransportOptionToCountryFarePrices { get; set; } // TransportOptionToCountryFarePrice.FK_TransportOptionToCountryFarePrice_TransportOption

        // Foreign keys
        public virtual TransportType TransportType { get; set; } // FK_TransportOption_TransportType

        public TransportOption()
        {
            Fares = new System.Collections.Generic.List<Fare>();
            Transports = new System.Collections.Generic.List<Transport>();
            TransportOptionToCityFarePrices = new System.Collections.Generic.List<TransportOptionToCityFarePrice>();
            TransportOptionToCountryFarePrices = new System.Collections.Generic.List<TransportOptionToCountryFarePrice>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
