// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Interface;

namespace Organization.Application.DTO.Entities
{

    // Transport
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class Transport : IEntity
    {
        public int ID { get; set; } // ID (Primary key)
        public int TransportOptionId { get; set; } // TransportOptionID
        public int PersonId { get; set; } // PersonID
        public string CarModel { get; set; } // CarModel (length: 100)
        public string CarColor { get; set; } // CarColor (length: 100)
        public string LicenseNumber { get; set; } // LicenseNumber (length: 100)
        public bool IsActive { get; set; } // IsActive
        public System.DateTime Created { get; set; } // Created

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Location> Locations { get; set; } // Location.FK_Location_Transport
        public virtual System.Collections.Generic.ICollection<TransportToFareRelation> TransportToFareRelations { get; set; } // TransportToFareRelation.FK_TransportToFareRelation_Transport

        // Foreign keys
        public virtual Person Person { get; set; } // FK_Transport_Person
        public virtual TransportOption TransportOption { get; set; } // FK_Transport_TransportOption

        public Transport()
        {
            IsActive = false;
            Created = System.DateTime.Now;
            Locations = new System.Collections.Generic.List<Location>();
            TransportToFareRelations = new System.Collections.Generic.List<TransportToFareRelation>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
