// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Entities;

namespace Organization.Application.Repository.Context
{

    public interface IDispatchContext : System.IDisposable
    {
        System.Data.Entity.DbSet<Address> Addresses { get; set; } // Address
        System.Data.Entity.DbSet<AspNetUserClaim> AspNetUserClaims { get; set; } // AspNetUserClaims
        System.Data.Entity.DbSet<AspNetUserLogin> AspNetUserLogins { get; set; } // AspNetUserLogins
        System.Data.Entity.DbSet<City> Cities { get; set; } // City
        System.Data.Entity.DbSet<CountryPhoneCode> CountryPhoneCodes { get; set; } // CountryPhoneCode
        System.Data.Entity.DbSet<CountryRegion> CountryRegions { get; set; } // CountryRegion
        System.Data.Entity.DbSet<Coupon> Coupons { get; set; } // Coupon
        System.Data.Entity.DbSet<CustomerComplaint> CustomerComplaints { get; set; } // CustomerComplaint
        System.Data.Entity.DbSet<DistanceUnit> DistanceUnits { get; set; } // DistanceUnit
        System.Data.Entity.DbSet<Document> Documents { get; set; } // Document
        System.Data.Entity.DbSet<EmailTemplate> EmailTemplates { get; set; } // EmailTemplate
        System.Data.Entity.DbSet<Fare> Fares { get; set; } // Fares
        System.Data.Entity.DbSet<FareStatu> FareStatus { get; set; } // FareStatus
        System.Data.Entity.DbSet<FareToPersonRelation> FareToPersonRelations { get; set; } // FareToPersonRelation
        System.Data.Entity.DbSet<Location> Locations { get; set; } // Location
        System.Data.Entity.DbSet<MobileVerification> MobileVerifications { get; set; } // MobileVerification
        System.Data.Entity.DbSet<MoneyUnit> MoneyUnits { get; set; } // MoneyUnit
        System.Data.Entity.DbSet<Person> People { get; set; } // Person
        System.Data.Entity.DbSet<PersonDocument> PersonDocuments { get; set; } // PersonDocument
        System.Data.Entity.DbSet<PersonRole> PersonRoles { get; set; } // PersonRole
        System.Data.Entity.DbSet<PersonToCoupon> PersonToCoupons { get; set; } // PersonToCoupon
        System.Data.Entity.DbSet<Reason> Reasons { get; set; } // Reason
        System.Data.Entity.DbSet<ReasonType> ReasonTypes { get; set; } // ReasonType
        System.Data.Entity.DbSet<Role> Roles { get; set; } // Role
        System.Data.Entity.DbSet<StateProvince> StateProvinces { get; set; } // StateProvince
        System.Data.Entity.DbSet<Transport> Transports { get; set; } // Transport
        System.Data.Entity.DbSet<TransportOption> TransportOptions { get; set; } // TransportOption
        System.Data.Entity.DbSet<TransportOptionToCityFarePrice> TransportOptionToCityFarePrices { get; set; } // TransportOptionToCityFarePrice
        System.Data.Entity.DbSet<TransportOptionToCountryFarePrice> TransportOptionToCountryFarePrices { get; set; } // TransportOptionToCountryFarePrice
        System.Data.Entity.DbSet<TransportToFareRelation> TransportToFareRelations { get; set; } // TransportToFareRelation
        System.Data.Entity.DbSet<TransportType> TransportTypes { get; set; } // TransportType

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);

        // Stored Procedures
        GetNearByVehiclesReturnModel GetNearByVehicles(decimal? lat, decimal? @long, int? transportOptionId, int? transportId);
        System.Threading.Tasks.Task<GetNearByVehiclesReturnModel> GetNearByVehiclesAsync(decimal? lat, decimal? @long, int? transportOptionId, int? transportId);

    }

}
// </auto-generated>
