// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Entities;

namespace Organization.Application.Repository.Context
{

    // PersonDocument
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class PersonDocumentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PersonDocument>
    {
        public PersonDocumentConfiguration()
            : this("dbo")
        {
        }

        public PersonDocumentConfiguration(string schema)
        {
            ToTable("PersonDocument", schema);
            HasKey(x => x.ID);

            Property(x => x.ID).HasColumnName(@"ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PersonId).HasColumnName(@"PersonID").IsRequired().HasColumnType("int");
            Property(x => x.DocumentId).HasColumnName(@"DocumentID").IsRequired().HasColumnType("int");
            Property(x => x.DocumentImage).HasColumnName(@"DocumentImage").IsRequired().HasColumnType("image").HasMaxLength(2147483647);
            Property(x => x.IsApproved).HasColumnName(@"IsApproved").IsRequired().HasColumnType("bit");
            Property(x => x.Created).HasColumnName(@"Created").IsRequired().HasColumnType("datetime");
            Property(x => x.Modified).HasColumnName(@"Modified").IsOptional().HasColumnType("datetime");

            // Foreign keys
            HasRequired(a => a.Document).WithMany(b => b.PersonDocuments).HasForeignKey(c => c.DocumentId).WillCascadeOnDelete(false); // FK_PersonDocuments_Documents
            HasRequired(a => a.Person).WithMany(b => b.PersonDocuments).HasForeignKey(c => c.PersonId).WillCascadeOnDelete(false); // FK_PersonDocuments_Person
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
