// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Entities;

namespace Organization.Application.Repository.Context
{

    // PersonRole
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class PersonRoleConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PersonRole>
    {
        public PersonRoleConfiguration()
            : this("dbo")
        {
        }

        public PersonRoleConfiguration(string schema)
        {
            ToTable("PersonRole", schema);
            HasKey(x => x.ID);

            Property(x => x.ID).HasColumnName(@"ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PersonId).HasColumnName(@"PersonID").IsRequired().HasColumnType("int");
            Property(x => x.RoleId).HasColumnName(@"RoleID").IsRequired().HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.Person).WithMany(b => b.PersonRoles).HasForeignKey(c => c.PersonId).WillCascadeOnDelete(false); // FK_PersonRole_Person
            HasRequired(a => a.Role).WithMany(b => b.PersonRoles).HasForeignKey(c => c.RoleId).WillCascadeOnDelete(false); // FK_PersonRole_Role
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
