// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Entities;

namespace Organization.Application.Repository.Context
{

    // PersonToCoupon
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class PersonToCouponConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PersonToCoupon>
    {
        public PersonToCouponConfiguration()
            : this("dbo")
        {
        }

        public PersonToCouponConfiguration(string schema)
        {
            ToTable("PersonToCoupon", schema);
            HasKey(x => x.ID);

            Property(x => x.ID).HasColumnName(@"ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PersonId).HasColumnName(@"PersonID").IsRequired().HasColumnType("int");
            Property(x => x.CouponId).HasColumnName(@"CouponID").IsRequired().HasColumnType("int");
            Property(x => x.FareId).HasColumnName(@"FareID").IsOptional().HasColumnType("int");
            Property(x => x.ActiveAsOf).HasColumnName(@"ActiveAsOf").IsOptional().HasColumnType("datetime");

            // Foreign keys
            HasOptional(a => a.Fare).WithMany(b => b.PersonToCoupons).HasForeignKey(c => c.FareId).WillCascadeOnDelete(false); // FK_PersonToCoupon_Fares
            HasRequired(a => a.Coupon).WithMany(b => b.PersonToCoupons).HasForeignKey(c => c.CouponId).WillCascadeOnDelete(false); // FK_PersonToCoupon_Coupon
            HasRequired(a => a.Person).WithMany(b => b.PersonToCoupons).HasForeignKey(c => c.PersonId).WillCascadeOnDelete(false); // FK_PersonToCoupon_Person
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
