// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Entities;

namespace Organization.Application.Repository.Context
{

    // Transport
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class TransportConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Transport>
    {
        public TransportConfiguration()
            : this("dbo")
        {
        }

        public TransportConfiguration(string schema)
        {
            ToTable("Transport", schema);
            HasKey(x => x.ID);

            Property(x => x.ID).HasColumnName(@"ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.TransportOptionId).HasColumnName(@"TransportOptionID").IsRequired().HasColumnType("int");
            Property(x => x.PersonId).HasColumnName(@"PersonID").IsRequired().HasColumnType("int");
            Property(x => x.CarModel).HasColumnName(@"CarModel").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.CarColor).HasColumnName(@"CarColor").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.LicenseNumber).HasColumnName(@"LicenseNumber").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.IsActive).HasColumnName(@"IsActive").IsRequired().HasColumnType("bit");
            Property(x => x.Created).HasColumnName(@"Created").IsRequired().HasColumnType("datetime");

            // Foreign keys
            HasRequired(a => a.Person).WithMany(b => b.Transports).HasForeignKey(c => c.PersonId).WillCascadeOnDelete(false); // FK_Transport_Person
            HasRequired(a => a.TransportOption).WithMany(b => b.Transports).HasForeignKey(c => c.TransportOptionId).WillCascadeOnDelete(false); // FK_Transport_TransportOption
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
