// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.61
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using Organization.Application.DTO.Entities;

namespace Organization.Application.Repository.Context
{

    // TransportOption
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class TransportOptionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TransportOption>
    {
        public TransportOptionConfiguration()
            : this("dbo")
        {
        }

        public TransportOptionConfiguration(string schema)
        {
            ToTable("TransportOption", schema);
            HasKey(x => x.ID);

            Property(x => x.ID).HasColumnName(@"ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.TransportTypeId).HasColumnName(@"TransportTypeID").IsRequired().HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.TransportType).WithMany(b => b.TransportOptions).HasForeignKey(c => c.TransportTypeId).WillCascadeOnDelete(false); // FK_TransportOption_TransportType
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
